Repository Cal-CS-61A-Staff/scheme_editor, pull requests merged in 2019-04, with the labels that each got.

#99 Debug limiter should be higher
  editor/log.py
  questions.scm
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#95 Typo
  editor/special_forms.py
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#97 Licences and stuff
  editor/libraries/mistune.py
  editor/static/ace/src-min-noconflict/ace.js
  editor/static/goldenlayout.js
  editor/static/select2.full.min.js
  editor/static/select2.min.css
  editor/static/svg-pan-zoom.js
  editor/static/svg.js
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#96 Turtle graphics
  .idea/inspectionProfiles/Project_Default.xml
  editor/css_colors.py
  editor/execution.py
  editor/graphics.py
  editor/log.py
  editor/scheme_exceptions.py
  editor/static/scripts/editor.js
  editor/static/scripts/env_diagram.js
  editor/static/scripts/event_handler.js
  editor/static/scripts/layout.js
  editor/static/scripts/output.js
  editor/static/scripts/state_handler.js
  editor/static/scripts/turtle_graphics.js
  editor/static/scripts/turtle_graphics_worker.js
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#103 Made it complain at you when you stop the editor process.
  editor/local_server.py
  editor/static/index.html
  editor/static/scripts/editor.js
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#98 Better parse errors
  editor/execution.py
  editor/static/scripts/editor.js
  editor/static/scripts/output.js
  questions.scm
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#100 Fixed bug with load.
  editor/special_forms.py
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#104 Automatic Python 3.5 transpilation
  editor/local_server.py
  editor/log.py
  editor/ok_interface.py
  strip_annotations
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#94 Do not cache test modules
  editor/ok_interface.py
Labels: Priority: High, Status: Review Needed, Type: Bug

#105 Fixed integer?
  editor/type_checking.py
Labels: Priority: High, Status: Review Needed, Type: Bug

#106 Fixed MathProcedures.
  editor/environment.py
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#108 Changed behavior of quasiquotation.
  editor/special_forms.py
Labels: Priority: Medium, Status: Review Needed, Type: Impoverishment

#126 Get rid of extra thread and use a separate process when we can't kill gracefully
  editor/local_server.py
  editor/ok_interface.py
  editor/runtime_limiter.py
Labels: Priority: High, Status: Review Needed, Type: Bug

#119 Handle comments on newlines better
  editor/format_parser.py
  editor/formatter.py
  editor/lexer.py
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement
